/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard.records'
import { Route as DashboardPrescriptionsRouteImport } from './routes/dashboard.prescriptions'
import { Route as DashboardPharmacyRouteImport } from './routes/dashboard.pharmacy'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard.patients'
import { Route as DashboardLabRouteImport } from './routes/dashboard.lab'
import { Route as DashboardDoctorsRouteImport } from './routes/dashboard.doctors'
import { Route as DashboardDepartmentsRouteImport } from './routes/dashboard.departments'
import { Route as DashboardConsultationsRouteImport } from './routes/dashboard.consultations'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard.appointments'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsRoute = DashboardPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacyRoute = DashboardPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLabRoute = DashboardLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsRoute = DashboardDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepartmentsRoute = DashboardDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConsultationsRoute = DashboardConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/consultations': typeof DashboardConsultationsRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/doctors': typeof DashboardDoctorsRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/prescriptions': typeof DashboardPrescriptionsRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/consultations'
    | '/dashboard/departments'
    | '/dashboard/doctors'
    | '/dashboard/lab'
    | '/dashboard/patients'
    | '/dashboard/pharmacy'
    | '/dashboard/prescriptions'
    | '/dashboard/records'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/consultations'
    | '/dashboard/departments'
    | '/dashboard/doctors'
    | '/dashboard/lab'
    | '/dashboard/patients'
    | '/dashboard/pharmacy'
    | '/dashboard/prescriptions'
    | '/dashboard/records'
    | '/dashboard/users'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/appointments'
    | '/dashboard/billing'
    | '/dashboard/consultations'
    | '/dashboard/departments'
    | '/dashboard/doctors'
    | '/dashboard/lab'
    | '/dashboard/patients'
    | '/dashboard/pharmacy'
    | '/dashboard/prescriptions'
    | '/dashboard/records'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prescriptions': {
      id: '/dashboard/prescriptions'
      path: '/prescriptions'
      fullPath: '/dashboard/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy': {
      id: '/dashboard/pharmacy'
      path: '/pharmacy'
      fullPath: '/dashboard/pharmacy'
      preLoaderRoute: typeof DashboardPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lab': {
      id: '/dashboard/lab'
      path: '/lab'
      fullPath: '/dashboard/lab'
      preLoaderRoute: typeof DashboardLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors': {
      id: '/dashboard/doctors'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/departments': {
      id: '/dashboard/departments'
      path: '/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof DashboardDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/consultations': {
      id: '/dashboard/consultations'
      path: '/consultations'
      fullPath: '/dashboard/consultations'
      preLoaderRoute: typeof DashboardConsultationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardConsultationsRoute: typeof DashboardConsultationsRoute
  DashboardDepartmentsRoute: typeof DashboardDepartmentsRoute
  DashboardDoctorsRoute: typeof DashboardDoctorsRoute
  DashboardLabRoute: typeof DashboardLabRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardPharmacyRoute: typeof DashboardPharmacyRoute
  DashboardPrescriptionsRoute: typeof DashboardPrescriptionsRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardConsultationsRoute: DashboardConsultationsRoute,
  DashboardDepartmentsRoute: DashboardDepartmentsRoute,
  DashboardDoctorsRoute: DashboardDoctorsRoute,
  DashboardLabRoute: DashboardLabRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardPharmacyRoute: DashboardPharmacyRoute,
  DashboardPrescriptionsRoute: DashboardPrescriptionsRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
